Video Game Shop V2/video_game_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('games/', include('games.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
]

games/urls.py
from django.urls import path

from . import views

# app_name = "games"

urlpatterns = [
    path('wishlist', views.WishListView.as_view(), name='wish_list'),
    path('search/', views.SearchResultsListView.as_view(), name='search_results'),
    path('<str:platform_name>', views.PlatformView.as_view(), name='games_list'),
    path('game/<int:pk>', views.GameDetailView.as_view(), name='single_game'),
    path('wishlist/<int:pk>/', views.add_remove_to_wishlist,
         name='add_remove_to_wishlist'),
]

orders/urls.py
from django.urls import path

from orders import views


urlpatterns = [
    path('invoice/<int:pk>/', views.AdminOrderPdf.as_view(), name='invoice'),
    path('', views.OrdersView.as_view(), name='orders'),
    path('checkout/payment', views.payment_view, name='payment'),
    path('checkout-coupon/apply', views.add_coupon_view, name='checkout-coupon'),
    path('checkout', views.checkout_view, name='checkout'),
    path('shopping-cart', views.CartSummaryView.as_view(), name='shopping-cart'),
    path('add-to-cart/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:pk>/',
         views.remove_from_cart, name='remove_from_cart'),
    path('remove-item-from-cart/<int:pk>/',
         views.remove_item_from_cart, name='remove_item_from_cart')
]

video_game_store_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('games/', include('games.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),
]

Video Game Shop V2/orders/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.utils import timezone
from django_countries.fields import CountryField

from games.models import Game

# Create your models here.

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    ordered = models.BooleanField(default=False)

    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.quantity} of {self.game.title}'

    def get_total_cart_item_price(self):
        return self.game.price_per_unit * self.quantity


class Order(models.Model):

    ORDER_CHOICES = (
    ('p', 'Payment Recieved'),
    ('pe', 'Pending'),
    ('pa', 'Packing'),
    ('s', 'Shippped'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    games = models.ManyToManyField(OrderItem)

    start_date = models.DateTimeField(auto_now_add=True)

    ordered_date = models.DateTimeField(timezone.now())

    ordered = models.BooleanField(default=False)

    order_status = models.CharField(
        max_length=2,
        choices=ORDER_CHOICES,
        default='pe',
    )

    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)

    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)

    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.user.username

    def get_total_cart_price(self):
        x = 0
        
        for order_item in self.games.all():
            x += order_item.game.price_per_unit * order_item.quantity
        
        if self.coupon:
            x -= self.coupon.amount    
        
        return x

    def get_total_cart_quantity(self):
        x = 0
        
        for order_item in self.games.all():
            x += order_item.quantity
       
        return x
    
    def get_generate_invoice_url(self):
        return reverse("invoice", kwargs={
            'pk': self.pk
        })


class Address(models.Model):
    STATE_CHOICES = (("AL","AL"),("AK","AK"),("AZ","AZ"),("AR","AR"),("CA","CA"),("CO","CO"),("CT","CT"),("DE","DE"),("FL","FL"),("GA","GA"),("HI","HI"),("ID","ID"),("IL","IL"),("IN","IN"),("IA","IA"),("KS","KS"),("KY","KY"),("LA","LA"),("ME","ME"),("MD","MD"),("MA","MA"),("MI","MI"),("MN","MN"),("MS","MS"),("MO","MO"),("MT","MT"),("NE","NE"),("NV","NV"),("NH","NH"),("NJ","NJ"),("NM","NM"),("NY","NY"),("NC","NC"),("ND","ND"),("OH","OH"),("OK","OK"),("OR","OR"),("PA","PA"),("RI","RI"),("SC","SC"),("SD","SD"),("TN","TN"),("TX","TX"),("UT","UT"),("VT","VT"),("VA","VA"),("WA","WA"),("WV","WV"),("WI","WI"),("WY","WY"))

    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    address = models.CharField(max_length=1000,  default="")

    optional_address = models.CharField(max_length=1000,  default="")

    country = CountryField(multiple=False)

    city = models.CharField(max_length=50,  default="")

    zip = models.CharField(max_length=10,  default="")

    address_type = models.CharField(max_length=8)

    state = models.CharField(
    max_length=2,
    choices=STATE_CHOICES,
    default='',
    )

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.DecimalField( max_digits=5, decimal_places=2, default=0.00)

    def __str__(self):
        return self.code.upper()


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.DecimalField( max_digits=5, decimal_places=2, default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

games/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django.utils import timezone
from django_countries.fields import CountryField


PLATFORM_CHOICES = (
    ('X', 'Xbox'),
    ('PS', 'PS4'),
    ('S', 'Switch'),
    ('PC', 'PC'),
)


class Game(models.Model):

    title = models.CharField(max_length=100)

    description = models.CharField(max_length=1000,  default="")

    release_date = models.DateField()

    developers = ArrayField(models.CharField(
        max_length=200),  default=list, blank=True)

    price_per_unit = models.DecimalField(
        max_digits=5, decimal_places=2, default=59.99)

    platform = models.CharField(
        choices=PLATFORM_CHOICES, default="", max_length=2)

    genre_tages = ArrayField(models.CharField(
        max_length=200),  default=list, blank=True)

    box_art = models.CharField(max_length=100)

    def get_add_to_cart_url(self):
        return reverse("add_to_cart", kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("remove_from_cart", kwargs={
            'pk': self.pk
        })

    def get_add_remove_to_wishlist_url(self):
        return reverse("add_remove_to_wishlist", kwargs={
            'pk': self.pk
        })

    def get_add_to_wishlist_url(self):
        return reverse("add_to_wishlist", kwargs={
            'pk': self.pk
        })

    def get_remove_from_wishlist_url(self):
        return reverse("remove_from_wishlist", kwargs={
            'pk': self.pk
        })

    def get_platform_name(self, platform):
        return PLATFORM_CHOICES[platform]

    def __str__(self):
        return self.title


class WishList(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

    wished_game = models.ForeignKey(Game, on_delete=models.CASCADE)

    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.wished_game.title

Video Game Shop V2/orders/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class CheckoutForm(forms.Form):
  STATE_CHOICES = (("AL","Alabama"),("AK","Alaska"),("AZ","Arizona"),("AR","Arkansas"),("CA","California"),("CO","Colorado"),("CT","Connecticut"),("DE","Delaware"),("FL","Florida"),("GA","Georgia"),("HI","Hawaii"),("ID","Idaho"),("IL","Illinois"),("IN","Indiana"),("IA","Iowa"),("KS","Kansas"),("KY","Kentucky"),("LA","Louisiana"),("ME","Maine"),("MD","Maryland"),("MA","Massachusetts"),("MI","Michigan"),("MN","Minnesota"),("MS","Mississippi"),("MO","Missouri"),("MT","Montana"),("NE","Nebraska"),("NV","Nevada"),("NH","New Hampshire"),("NJ","New Jersey"),("NM","New Mexico"),("NY","New York"),("NC","North Carolina"),("ND","North Dakota"),("OH","Ohio"),("OK","Oklahoma"),("OR","Oregon"),("PA","Pennsylvania"),("RI","Rhode Island"),("SC","South Carolina"),("SD","South Dakota"),("TN","Tennessee"),("TX","Texas"),("UT","Utah"),("VT","Vermont"),("VA","Virginia"),("WA","Washington"),("WV","West Virginia"),("WI","Wisconsin"),("WY","Wyoming"))

  address = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': '1234 Main St',
    'class': 'form-control',
    'id': 'address'
  }), max_length=100 )
  optional_address = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Apartment or suite',
    'class': 'form-control',
    'id': 'optional_address'
  }), label='Address 2 (Optional)', max_length=100, required=False )
  country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
    'class': 'custom-select d-block w-100',
    'id': 'country'
  }))
  zip = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Zip',
    'class': 'form-control',
    'id': 'zip'
  }))
  state = forms.CharField(widget=forms.Select(choices=STATE_CHOICES, attrs={
    'class': 'custom-select d-block w-100',
    'id': 'state'
  }))
  city = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'City',
    'class': 'form-control',
    'id': 'city'
  }))
  same_billing_address = forms.BooleanField(required=False)

  billing_address = forms.CharField(widget=forms.TextInput(attrs={
  'placeholder': '1234 Main St',
  'class': 'form-control',
    'id': 'billing_address'
  }), max_length=100, required=False )
  billing_optional_address = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Apartment or suite',
    'class': 'form-control',
    'id': 'billing_optional_address'
  }), label='Address 2 (Optional)', max_length=100, required=False )
  billing_country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
    'class': 'custom-select d-block w-100',
    'id': 'billing_country'
  }), required=False)
  billing_zip = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Zip',
    'class': 'form-control',
    'id': 'billing_zip'
  }), required=False)
  billing_state = forms.CharField(widget=forms.Select(choices=STATE_CHOICES, attrs={
    'class': 'custom-select d-block w-100',
    'id': 'billing_state'
  }))
  billing_city = forms.CharField(widget=forms.TextInput(attrs={
  'placeholder': 'City',
  'class': 'form-control',
  'id': 'billing_city'
  }), required=False)

class CouponForm(forms.Form):
  code = forms.CharField(widget=forms.TextInput(attrs={
      'class': 'form-control',
      'placeholder': 'Promo code'
  }))

orders/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


class CheckoutForm(forms.Form):
    STATE_CHOICES = (("AL", "Alabama"), ("AK", "Alaska"), ("AZ", "Arizona"), ("AR", "Arkansas"), ("CA", "California"), ("CO", "Colorado"), ("CT", "Connecticut"), ("DE", "Delaware"), ("FL", "Florida"), ("GA", "Georgia"), ("HI", "Hawaii"), ("ID", "Idaho"), ("IL", "Illinois"), ("IN", "Indiana"), ("IA", "Iowa"), ("KS", "Kansas"), ("KY", "Kentucky"), ("LA", "Louisiana"), ("ME", "Maine"), ("MD", "Maryland"), ("MA", "Massachusetts"), ("MI", "Michigan"), ("MN", "Minnesota"), ("MS", "Mississippi"), ("MO", "Missouri"), ("MT",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Montana"), ("NE", "Nebraska"), ("NV", "Nevada"), ("NH", "New Hampshire"), ("NJ", "New Jersey"), ("NM", "New Mexico"), ("NY", "New York"), ("NC", "North Carolina"), ("ND", "North Dakota"), ("OH", "Ohio"), ("OK", "Oklahoma"), ("OR", "Oregon"), ("PA", "Pennsylvania"), ("RI", "Rhode Island"), ("SC", "South Carolina"), ("SD", "South Dakota"), ("TN", "Tennessee"), ("TX", "Texas"), ("UT", "Utah"), ("VT", "Vermont"), ("VA", "Virginia"), ("WA", "Washington"), ("WV", "West Virginia"), ("WI", "Wisconsin"), ("WY", "Wyoming"))

    address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St',
        'class': 'form-control',
        'id': 'address'
    }), max_length=100)
    optional_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or suite',
        'class': 'form-control',
        'id': 'optional_address'
    }), label='Address 2 (Optional)', max_length=100, required=False)
    country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100',
        'id': 'country'
    }))
    zip = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Zip',
        'class': 'form-control',
        'id': 'zip'
    }))
    state = forms.CharField(widget=forms.Select(choices=STATE_CHOICES, attrs={
        'class': 'custom-select d-block w-100',
        'id': 'state'
    }))
    city = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'City',
        'class': 'form-control',
        'id': 'city'
    }))
    same_billing_address = forms.BooleanField(required=False)

    billing_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': '1234 Main St',
        'class': 'form-control',
        'id': 'billing_address'
    }), max_length=100, required=False)
    billing_optional_address = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Apartment or suite',
        'class': 'form-control',
        'id': 'billing_optional_address'
    }), label='Address 2 (Optional)', max_length=100, required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100',
        'id': 'billing_country'
    }), required=False)
    billing_zip = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Zip',
        'class': 'form-control',
        'id': 'billing_zip'
    }), required=False)
    billing_state = forms.CharField(widget=forms.Select(choices=STATE_CHOICES, attrs={
        'class': 'custom-select d-block w-100',
        'id': 'billing_state'
    }))
    billing_city = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'City',
        'class': 'form-control',
        'id': 'billing_city'
    }), required=False)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code'
    }))

templates/orders.html
{% extends 'base.html' %}{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
  <div class="container">
    <h1 class="title-page text-center">My Orders</h1>
  </div>
  <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<br /><br />

<section class="section-content padding-y">
  <div class="container">
    {% if orders %} {% for order in orders %}
    <div class="row justify-content-center">
      <main class="col-md-9">
        <div class="card">
          <table id="table" class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" width="220">Order Placed</th>
                <th scope="col" class="text-right" width="200">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for order_item in order.games.all %}
              <tr id="cartItemRow{{order_item.id}}">
                <td>
                  <figure class="itemside">
                    <div class="aside">
                      <img src="{{ order_item.game.box_art }}" class="img-sm" />
                    </div>
                    <figcaption class="info">
                      <a href="#" class="title text-dark"
                        >{{order_item.game.title}}</a
                      >
                      <p class="text-muted small">
                        Platform: {{order_item.game.get_platform_display}}<br />
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td class="text-center">
                  <span id="cart-count{{order_item.game.id}}" class="">
                    {{order_item.quantity}}
                  </span>
                </td>
                <td>
                  <div class="price-wrap">
                    <var id="cartItemTotal{{order_item.game.id}}" class="price"
                      >${{order_item.get_total_cart_item_price}}</var
                    >
                    <small class="text-muted">
                      ${{order_item.game.price_per_unit}} each
                    </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td>
                  <h6 class="">
                    {{ order.ordered_date }}
                  </h6>
                </td>
                <td class="text-right">
                  <h6 class="">
                    <span class="badge badge-pill badge-primary"
                      >Status: {{ order.get_order_status_display }}</span
                    >
                  </h6>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

          <div class="card-body border-top">
            <a
              href="{{ order.get_generate_invoice_url }}"
              class="btn btn-primary float-md-right"
            >
              Generate Invoice
              <span class="ml-2">
                <i class="fas fa-receipt"></i>
              </span>
            </a>
          </div>
        </div>
        <!-- card.// -->
      </main>
    </div>
  </div>
  {% endfor %} {% else %}
  <h2 class="mt-5 text-white text-center">You have no recent orders</h2>
  {% endif %}
</section>
{% endblock %}

templates/search_results.html
{% extends 'base.html' %} {% load static %} {% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
  <div class="container">
    <h1 class="title-page text-center">Search Results</h1>
  </div>
  <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<div class="container">
  {% if game_list %}
  <div class="center">
    <div class="row justify-content-center">
      {% for game in game_list %}
      <div class="col-md-3">
        <figure class="card card-product-grid">
          <div class="img-wrap">
            <img src="{{ game.box_art }}" />
            <a class="btn-overlay" href="{% url 'single_game' game.id %}"
              ><i class="fa fa-search-plus"></i> Game Details</a
            >
          </div>
          <figcaption class="info-wrap border-top">
            <div class="text-center">
              <b class="title">{{ game.title }}</b>
              <br />
              <var class="price">{{ game.get_platform_display }}</var>
              <br />
              <var class="price">Price: {{ game.price_per_unit }}</var>
            </div>

            <div class="price mt-2">
              <!-- price-wrap.// -->
              <a
                href="#"
                onclick="addToCart(event, '{{ game.get_add_to_cart_url }}')"
                class="btn btn-block btn-outline-primary float-right"
              >
                <span class="text">Add to cart</span>
                <i class="fas fa-shopping-cart"></i>
              </a>
            </div>
            <!-- price-wrap.// -->
          </figcaption>
        </figure>
        <!-- card // -->
      </div>

      <!-- Modal -->
      <div
        class="modal fade mt-5 rounded-0"
        id="modal{{ game.id }}"
        tabindex="-1"
        role="dialog"
        aria-labelledby="ModalLongTitle"
        aria-hidden="true"
      >
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div
              class="modal-body text-center gamesModal border-top-0 border-bottom-0"
            >
              <div class="row text-white ">
                <div>
                  <div class="col">
                    <img
                      src="{{ game.box_art }}"
                      class="shadow-lg "
                      alt="..."
                      style="height:375px; width:300px"
                    />
                  </div>
                  <div class="col">
                    <div class="toast-body">
                      <h3 class="mt-0">{{ game.title }}</h3>
                    </div>
                    <div class="toast-body">
                      <span
                        class="mt-0 badge badge-pill badge-success rounded-0 shadow-lg"
                        >Developer: {{ game.developer }}</span
                      >
                      <span
                        class="mt-0 badge badge-pill badge-success rounded-0 shadow-lg"
                        >Release Date: {{ game.release_date }}</span
                      >
                    </div>
                    <div class="toast-body">
                      {{ game.description }}
                    </div>
                    <div class="toast-body">
                      {% for tag in game.genre_tages %}
                      <span
                        class="badge badge-pill badge-primary rounded-0 shadow-lg"
                      >
                        {{ tag }}
                      </span>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="modal-footer bg-dark border-top-0 rounded-0">
              <a
                href="{{ game.get_add_to_cart_url }}"
                class="btn btn-primary btn-lg btn-block shadow-lg"
              >
                $60 - Add to Cart
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% else %}
  <p class="text-center text-white">No Games Found! Please Try Again!</p>
  {% endif %}
</div>
{% endblock %}

templates/shopping_cart.html
{% extends 'base.html' %} {% load static %} {% block content %}
<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
  <div class="container">
    <h2 class="title-page text-center">Shopping cart</h2>
  </div>
  <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-content padding-y">
  <div class="container">
    <div class="row">
      <main class="col-md-9">
        <div class="card">
          <table id="table" class="table table-borderless table-shopping-cart">
            <thead class="text-muted">
              <tr class="small text-uppercase">
                <th scope="col">Product</th>
                <th scope="col" width="120">Quantity</th>
                <th scope="col" width="120">Price</th>
                <th scope="col" class="text-right" width="200"></th>
              </tr>
            </thead>
            <tbody>
              {% for order_item in order.games.all %}
              <tr id="cartItemRow{{order_item.id}}">
                <td>
                  <figure class="itemside">
                    <div class="aside">
                      <img src="{{ order_item.game.box_art }}" class="img-sm" />
                    </div>
                    <figcaption class="info">
                      <a href="#" class="title text-dark"
                        >{{order_item.game.title}}</a
                      >
                      <p class="text-muted small">
                        Platform: {{order_item.game.get_platform_display}}<br />
                      </p>
                    </figcaption>
                  </figure>
                </td>
                <td>
                  <a
                    href="#"
                    onclick="removeFromCart(event, '{{ order_item.game.get_remove_from_cart_url }}')"
                    class=""
                  >
                    <i class="fas fa-minus"></i>
                  </a>
                  <span id="cart-count{{order_item.game.id}}" class="">
                    {{order_item.quantity}}
                  </span>
                  <a
                    href="#"
                    onclick="addToCartInCart(event, '{{ order_item.game.get_add_to_cart_url }}')"
                    class=""
                  >
                    <i class="fas fa-plus"></i>
                  </a>
                </td>
                <td>
                  <div class="price-wrap">
                    <var id="cartItemTotal{{order_item.game.id}}" class="price"
                      >${{order_item.get_total_cart_item_price}}</var
                    >
                    <small class="text-muted">
                      ${{order_item.game.price_per_unit}} each
                    </small>
                  </div>
                  <!-- price-wrap .// -->
                </td>
                <td class="text-right">
                  <a
                    href=""
                    onclick="removeAllFromCart(event, '{{ order_item.get_remove_item_from_cart_url }}')"
                    class="btn btn-light"
                  >
                    Remove</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>

          <div class="card-body border-top">
            <a
              href="{% url 'checkout' %}"
              class="btn btn-primary float-md-right"
            >
              Make Purchase <i class="fa fa-chevron-right"></i>
            </a>
            <a href="{% url 'home' %}" class="btn btn-light">
              <i class="fa fa-chevron-left"></i> Continue shopping
            </a>
          </div>
        </div>
        <!-- card.// -->

        <div class="alert alert-success mt-3">
          <p class="icontext">
            <i class="icon text-success fa fa-truck"></i> Free Delivery within
            1-2 weeks
          </p>
        </div>
      </main>
      <!-- col.// -->
      <aside class="col-md-3">
        <!-- card .// -->
        <div class="card">
          <div class="card-body">
            <dl class="dlist-align">
              <dt>Total in Cart:</dt>
              <dd class="text-right h5">
                <strong id="totalCartPrice"
                  >${{order.get_total_cart_price_no_coupon}}</strong
                >
              </dd>
            </dl>
            <hr />
            <p class="text-center mb-3">
              <i class="fab fa-cc-stripe fa-3x"></i>
            </p>
          </div>
          <!-- card-body.// -->
        </div>
        <!-- card .// -->
      </aside>
      <!-- col.// -->
    </div>
  </div>
  <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

templates/wishlist.html
{% extends 'base.html' %}{% block content %}

<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
  <div class="container">
    <h1 class="title-page text-center">Wishlist</h1>
  </div>
  <!-- container //  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->

<section class="section-content padding-y">
  <div class="container">
    {% if games %} {% for game in games %}
    <div class="col-md-3">
      <figure class="card card-product-grid">
        <div class="img-wrap">
          <img src="{{ game.wished_game.box_art }}" />
          <a class="btn-overlay" href="{% url 'single_game' game.id %}"
            ><i class="fa fa-search-plus"></i> Game Details</a
          >
        </div>
        <figcaption class="info-wrap border-top">
          <div class="text-center">
            <b class="title">{{ game.wished_game.title }}</b>
            <br />
            <var class="price"
              >Price: {{ game.wished_game.price_per_unit }}</var
            >
          </div>

          <div class="price mt-2">
            <!-- price-wrap.// -->
            <form
              method="POST"
              action="{{ game.get_add_to_cart_url }}"
              class="form form-game-ajax"
            >
              {% csrf_token %}
              <button
                type="submit"
                class="btn btn-block btn-outline-primary float-right"
              >
                Add to cart
                <i class="fa fa-shopping-cart"></i>
              </button>
            </form>
          </div>
          <!-- price-wrap.// -->
        </figcaption>
      </figure>
      <!-- card // -->
    </div>

    {% endfor %} {% else %}
    <h2 class="mt-5 text-white text-center">No Games In Wishlist!</h2>
    {% endif %}
  </div>
</section>
{% endblock %}